### ISSUE TITLE
PERL6LIB seems to use ',' as separator now

### ISSUE THREAD

**Issue by jantz** [masak/ufo#24]
Hi,
The PERL6LIB separator seems to be changed from ':' to ','.
The generated Makefile fails.
In ufo the following line needs a change:
P6LIB  = $(PWD)/$(BLIB)/lib:$(PWD)/lib:$(PERL6LIB)

If you have changed this and PERL6LIB is empty make fails,
because of the trailing ','.

Can you please check.

**Comment by teodozjan** [comment]
Pull https://github.com/masak/ufo/pull/25 seems to fix issue at least on my machine

**Comment by teodozjan** [comment]
https://github.com/masak/ufo/commit/17c11b8eeadf477e1cc73d8f6a7218569da0dece

**Comment by jantz** [comment]
Can be closed of course :)
